### ISSUE TITLE
Pull in improvements from  jkbrzt/podcats

### ISSUE THREAD

**Issue by tiktuk** [jkbrzt/podcats#2]
There is a lot of useful fixes in the repo at https://github.com/ymomoi/podcats, I wonder if you could merge them and publish on PyPi?

I was about to make some of the same fixes myself and then saw they were already done. I would have asked @ymomoi but they don't have issues/messaging turned on…

Thanks for a nice program btw ☺️ .

**Comment by jkbrzt** [comment]
I'd be happy to merge the changes. @ymomoi do you wanna send a pull request?

Thanks, @tiktuk :) Just out of curiosity — what's your use case for this project?

**Comment by tiktuk** [comment]
Thanks ☺️.

I want to use it to be able to listen to audiobooks in my podcast app. I use Overcast and it supports uploading my own files but only individually and it's a chore when there is dozens of files…

So I had already thought about programming the same script but luckily found yours first 😄 .

**Comment by jkbrzt** [comment]
Sweet, I wrote it for exactly this purpose just for iTunes.

**Comment by tiktuk** [comment]
Yes, I'm looking forward to using it ☺️ .

**Comment by ymomoi** [comment]
Thanks for notification to me. OK, I'll make some pull requests. Please wait for a few days.

p.s.
I'm using this project, for listening radio recording files on iTunes 😄

**Comment by jkbrzt** [comment]
@ymomoi sounds great 👍

**Comment by jkbrzt** [comment]
Done. Released v0.3.0 on PyPi. Thanks 👍

**Comment by tiktuk** [comment]
Great, thanks ☺️ ! And cool with Python 3 support as well!
