### ISSUE TITLE
How can I get this to work with Cloudflare Tunnel?

### ISSUE THREAD

**Issue by tapatianbeast** [jkbrzt/podcats#27]
Terrific Job! I try to put 192.168.xxx & localhost:xxx but the cloudfare tunnel does not recognize it..

**Comment by pokulo** [comment]
Not sure what is your setup. But listening for local addresses might not work with a tunnel that is supposed to serve to the internet. Did you use `podcats serve --host localhost --port xxx`? Maybe try using the hostname of that machine having 192.168.xxx ip.
